In [42]:
import numpy as np
def normlize_data(data):
    mean=np.mean(data)
    std=np.std(data)
    normalized_data=[(x-mean)/std for x in data]
    return normalized_data

In [55]:
data = []
for i in range(0,100):
    data.append(np.random.randint(0,100))
print(data)

[76, 20, 59, 15, 56, 90, 89, 68, 6, 40, 0, 49, 95, 87, 33, 40, 3, 75, 65, 64, 67, 62, 93, 37, 58, 20, 87, 53, 39, 25, 91, 54, 10, 61, 19, 3, 65, 72, 76, 11, 59, 62, 23, 22, 40, 32, 76, 48, 83, 68, 31, 39, 61, 61, 59, 49, 65, 9, 86, 36, 23, 86, 13, 6, 29, 29, 44, 99, 59, 83, 58, 40, 89, 36, 1, 61, 36, 73, 78, 3, 34, 78, 99, 9, 40, 68, 11, 90, 94, 35, 77, 86, 14, 37, 36, 83, 26, 72, 55, 44]


In [33]:
print(normlize_data(data))
datas=normlize_data(data)

[-1.246366527746591, -0.31890431476973446, -1.1036800334424592, 1.0722890046955504, 1.2506471225757152, 0.3588565331748915, 0.037811920990595, 0.037811920990595, -0.14054619688956974, 1.0009457575434846, 0.39452815675092445, 0.1804984152947268, 1.4646768640319128, 1.1793038754236493, 1.42900524045588, 1.0722890046955504, 1.0722890046955504, -1.1393516570184923, 0.1091551681426609, -0.5329340562259322, -1.7457692578110522, 0.1091551681426609, -1.852784128539151, 1.42900524045588, 1.5003484876079458, 1.286318746151748, 0.8582592632393528, -0.4259191854978333, -0.21188944404163562, 0.1804984152947268, -0.5329340562259322, 0.9296025103914186, 0.1804984152947268, 0.3231849095988586, 0.8582592632393528, 1.393333616879847, -0.06920294973750384, -1.4247246456267557, 0.7155727689352209, -1.4247246456267557, -0.24756106761766855, 0.7155727689352209, 0.07348354456662795, -0.24756106761766855, 0.679901145359188, -1.3533813984746899, -1.852784128539151, 0.39452815675092445, -0.8183070448341957, -1.

In [34]:
print(np.mean(datas))
np.std(datas)

7.993605777301127e-17


1.0

In [35]:
def minmax_scaling(data):
    mins=min(data)
    maxs=max(data)
    norm_data=[(x-mins)/(maxs-mins) for x in data]
    return norm_data

In [36]:
print(minmax_scaling(data))

[0.21212121212121213, 0.47474747474747475, 0.25252525252525254, 0.8686868686868687, 0.9191919191919192, 0.6666666666666666, 0.5757575757575758, 0.5757575757575758, 0.5252525252525253, 0.8484848484848485, 0.6767676767676768, 0.6161616161616161, 0.9797979797979798, 0.898989898989899, 0.9696969696969697, 0.8686868686868687, 0.8686868686868687, 0.24242424242424243, 0.5959595959595959, 0.41414141414141414, 0.0707070707070707, 0.5959595959595959, 0.04040404040404041, 0.9696969696969697, 0.98989898989899, 0.9292929292929293, 0.8080808080808081, 0.4444444444444444, 0.5050505050505051, 0.6161616161616161, 0.41414141414141414, 0.8282828282828283, 0.6161616161616161, 0.6565656565656566, 0.8080808080808081, 0.9595959595959596, 0.5454545454545454, 0.16161616161616163, 0.7676767676767676, 0.16161616161616163, 0.494949494949495, 0.7676767676767676, 0.5858585858585859, 0.494949494949495, 0.7575757575757576, 0.18181818181818182, 0.04040404040404041, 0.6767676767676768, 0.3333333333333333, 0.26262626262

In [37]:
import numpy as np
sample_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
mean=np.mean(sample_array)
std_dev=np.std(sample_array)
standardized_array=(sample_array-mean)/std_dev
print("standardization array")
print(standardized_array)

standardization array
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [38]:
norm_log=[np.log(x) for x in data]

C:\Users\hp\AppData\Local\Temp\ipykernel_3412\4263611326.py:1: RuntimeWarning: divide by zero encountered in log
  norm_log=[np.log(x) for x in data]


In [39]:
norm_log

[3.044522437723423,
 3.8501476017100584,
 3.2188758248682006,
 4.454347296253507,
 4.51085950651685,
 4.189654742026425,
 4.04305126783455,
 4.04305126783455,
 3.9512437185814275,
 4.430816798843313,
 4.204692619390966,
 4.110873864173311,
 4.574710978503383,
 4.48863636973214,
 4.564348191467836,
 4.454347296253507,
 4.454347296253507,
 3.1780538303479458,
 4.07753744390572,
 3.713572066704308,
 1.9459101490553132,
 4.07753744390572,
 1.3862943611198906,
 4.564348191467836,
 4.584967478670572,
 4.5217885770490405,
 4.382026634673881,
 3.784189633918261,
 3.912023005428146,
 4.110873864173311,
 3.713572066704308,
 4.406719247264253,
 4.110873864173311,
 4.174387269895637,
 4.382026634673881,
 4.553876891600541,
 3.9889840465642745,
 2.772588722239781,
 4.330733340286331,
 2.772588722239781,
 3.8918202981106265,
 4.330733340286331,
 4.060443010546419,
 3.8918202981106265,
 4.31748811353631,
 2.8903717578961645,
 1.3862943611198906,
 4.204692619390966,
 3.4965075614664802,
 3.25809653802

In [40]:
from sklearn import preprocessing
norm=preprocessing.normalize([data])
norm

array([[0.03356175, 0.07511438, 0.03995446, 0.13744334, 0.14543423,
        0.10547977, 0.09109617, 0.09109617, 0.08310527, 0.13424698,
        0.10707795, 0.09748888, 0.1550233 , 0.14223787, 0.15342512,
        0.13744334, 0.13744334, 0.03835628, 0.09429252, 0.06552531,
        0.01118725, 0.09429252, 0.00639271, 0.15342512, 0.15662148,
        0.14703241, 0.12785427, 0.07031985, 0.07990892, 0.09748888,
        0.06552531, 0.13105062, 0.09748888, 0.10388159, 0.12785427,
        0.15182694, 0.08630163, 0.02557085, 0.12146155, 0.02557085,
        0.07831074, 0.12146155, 0.09269434, 0.07831074, 0.11986338,
        0.02876721, 0.00639271, 0.10707795, 0.05273989, 0.04155264,
        0.15022876, 0.09269434, 0.        , 0.11187248, 0.02077632,
        0.0223745 , 0.10867613, 0.04954353, 0.10388159, 0.1326488 ,
        0.1326488 , 0.03515992, 0.06552531, 0.06073078, 0.04155264,
        0.07990892, 0.08630163, 0.00639271, 0.10547977, 0.11506884,
        0.00639271, 0.11187248, 0.0223745 , 0.12

In [57]:
data=np.arange(50,100)
scaler = preprocessing.RobustScaler()
robust_df = scaler.fit_transform([data])
print(robust_df)
 
scaler = preprocessing.StandardScaler()
standard_df = scaler.fit_transform([data])
print(standard_df)
 
scaler = preprocessing.MinMaxScaler()
minmax_df = scaler.fit_transform([data])
print(minmax_df)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]


In [48]:
scaler = preprocessing.MinMaxScaler()
rescaledX = scaler.fit_transform([data])

In [49]:
rescaledX

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [52]:
from sklearn.preprocessing import StandardScaler
import pandas
import numpy

# data values
X =[data]

# scaler
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

# summarize transformed data
numpy.set_printoptions(precision=3)
print(rescaledX[0:6,:])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
